[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0"
crc = "3.0.0"
more-asserts = "0.3.0"
num_cpus = "1.13.1"
systemstat = "0.2.0"
libc = "0.2.89"

[target.'cfg(osunix)'.dependencies]
nix = "0.23"
signal-hook = "0.3.14"
<<<<<<< Updated upstream

[target.'cfg(oswindows)'.dependencies]
win-sys = "0.3"

[dependencies.windows-sys]
version = "0.42.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_Performance",
    "Win32_UI_WindowsAndMessaging",
]
=======
thread-id = "4.0.0"
>>>>>>> Stashed changes
