[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.0"
nix = "0.25.0"
libc = "0.2.132"
more-asserts = "0.3.0"
num_cpus = "1.13.1"
systemstat = "0.2.0"
